services:

  postgres:
    image: postgres:16.1
    container_name: postgres
    hostname: ${POSTGRES_HOST:-postgres}
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_DB: ${POSTGRES_DB:-ewm_analyzer} # Used temporarily at startup, doesn't affect other DBs
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - ./stuff/compose/initscripts:/docker-entrypoint-initdb.d
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres}" ]
      interval: 10s
      timeout: 5s
      retries: 10
