spring:
  application:
    name: collector

  kafka:
    bootstrap-servers: localhost:9092
    topics:
      user-action: stats.user-actions.v1
    properties:
      acks: all

grpc:
  server:
    port: 0

server:
  port: 0

logging:
  level:
    ru.practicum: DEBUG
    org.springframework.kafka: DEBUG
    io.grpc: DEBUG


