CREATE TABLE IF NOT EXISTS endpointhit
(
    id INTEGER GENERATED ALWAYS AS IDENTITY,
    app VARCHAR(255) NOT NULL,
    uri VARCHAR(255) NOT NULL,
    ip VARCHAR(39) NOT NULL,
    request_time TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW(),
    CONSTRAINT pk_endpoint_hit PRIMARY KEY (id)
);
