spring:
  application:
    name: comment-service

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
        format_sql: true

  sql:
    init:
      mode: always

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/ewm_comment
    username: postgres
    password: password

  cloud:
    openfeign:
      circuitbreaker:
        enabled: true

  jackson:
    serialization:
      write-dates-as-timestamps: false
    deserialization:
      adjust-dates-to-context-time-zone: false
    date-format: yyyy-MM-dd HH:mm:ss

resilience4j.circuitbreaker:
  configs:
    default:
      slidingWindowSize: 2
      failureRateThreshold: 50
      minimumNumberOfCalls: 2
      waitDurationInOpenState: 10000
      permittedNumberOfCallsInHalfOpenState: 2
      slidingWindowType: COUNT_BASED
      automaticTransitionFromOpenToHalfOpenEnabled: true
      slowCallRateThreshold: 100
      slowCallDurationThreshold: 60000
      ignoreExceptions:
        - ru.practicum.exception.dto.ApiError
  timelimiter:
    configs:
      values:
        timeout-duration: 7s

server:
  port: 0

logging:
  level:
    ru.practicum: DEBUG
    org.hibernate.tool.schema: DEBUG
