spring:
  cloud:
    gateway:
      discovery.locator.enabled: true
      routes:
        # user-service TODO until separated compleatly
        - id: user_service_route
          uri: lb://user-service
          predicates:
            - Path=/admin/users/**
        # main-service
        - id: main_service_route
          uri: lb://main-service
          predicates:
            - Path=/**
server:
  port: 8080

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.cloud.gateway.route.RouteDefinitionRouteLocator: DEBUG

