spring:
  cloud:
    gateway:
      discovery.locator.enabled: true
      routes:
        # user-service
        - id: user_service_route
          uri: lb://user-service
          predicates:
            - Path=/admin/users/**

        # comment-service
        - id: comment_service_route
          uri: lb://comment-service
          predicates:
            - Path=/admin/comments/**, /users/{userId}/comments/**, /events/{eventId}/comments/**

        # request-service
        - id: request_service_route
          uri: lb://request-service
          predicates:
            - Path=/users/{userId}/requests/**

        # event-service
        - id: event_service_route
          uri: lb://event-service
          predicates:
            - Path=/admin/events/**, /users/{userId}/events/**, /events/**, /admin/categories/**, /categories/**, /admin/compilations/**, /compilations/**
server:
  port: 8080

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.cloud.gateway.route.RouteDefinitionRouteLocator: DEBUG

