spring:
  application:
    name: stats-server

  main:
    banner-mode: off
  output:
    ansi:
      enabled: ALWAYS

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
        format_sql: true

  sql:
    init:
      mode: always

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:6541/stats_service
    username: admin
    password: admin

server:
  port: 0

logging:
  level:
    ru.practicum: DEBUG
    org.hibernate.tool.schema: DEBUG
